name: LobbySystem
version: 1.1
main: de.legan100.lobbysystem.LobbySystem
author: legan100
api-version: 1.16
commands:
  accept:
  boots:
  Build:
  fly:
  Spec:
  Spectator:
  v:
  Vanish:
  setspawn:
  setspawn1:
  setspawn2:
  setspawn3:
  setspawn4:
  update:
  lobbyver:
  lobbyversion:
  shop:
  datenschutz:
  setbau: